FROM node:21-alpine3.17
ENV NODE_ENV=develop
WORKDIR /app
# COPY package.json  ./
RUN yarn install --frozen-lockfile
# install pm2
RUN yarn global add pm2
COPY . .
EXPOSE 3000
CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]
