#docker compose for production
#docker-compose -f docker-compose.prod.yml up -d --build
version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - mogonetwork
  express-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: express-server
    volumes:
      - .:/app
    ports:
      - 3005:3000
    networks:
      - mogonetwork
networks:
  mogonetwork:
    driver: bridge