version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - mogonetwork
  express-server:
    # build for dockerfile.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-server
    volumes:
      - .:/app
      #watch change nodemodule and build again
     # - /app/node_modules
    ports:
      - 3005:3000
    networks:
      - mogonetwork
networks:
  mogonetwork:
    driver: bridge